Description:  Template para el cluster.

Parameters: 
  BucketS3: 
    Description: "URL del Bucket donde estaran almacenado los templates templates"
    Type: String
  
  EC2TYPE:
    Description: "Tipo EC2"
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.medium
      - t2.large

Resources:
  NetworkStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: 
        !Join
          - ""
          - - !Ref BucketS3
            - "/Network/network.yml"
  LoadBalancerStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: 
        !Join
          - ""
          - - !Ref BucketS3
            - "/Network/loadbalancer.yml"
      Parameters:
          RefSubnetPublica: !GetAtt NetworkStack.Outputs.RefSubnetPublic1
          RefSG : !GetAtt NetworkStack.Outputs.RefPublicSG
          RefVPC : !GetAtt NetworkStack.Outputs.RefVPC
          ParentStackName : !Ref AWS::StackName
          EC2TYPE : !Ref AWS::EC2TYPE
          Keyname : "Key"
          ECSCluster : !GetAtt NetworkStack.Outputs.ECSCluster
          taskdefinition : !GetAtt NetworkStack.Outputs.taskdefinition
